apiVersion: v2
name: lbaas-for-all
description: A Helm chart to deploy all required lbaas components 

type: application

version: 0.0.1

appVersion: "0.0.1"

dependencies:
- name: load-balancer-operator 
  version: "v0.0.2"
  repository: "https://infratographer.github.io/charts"
  condition: infratographer.lbaas.operator.enabled
- name: load-balancer-api 
  version: "v0.0.13"
  repository: "https://infratographer.github.io/charts"
  condition: infratographer.lbaas.api.enabled
- name: nats
  repository: https://nats-io.github.io/k8s/helm/charts/
  version: 0.19.12
- name: cockroachdb
  repository: https://charts.cockroachdb.com/
  version: 10.0.7

